"""Embed only the small test graph/metadata; the worker generates its 10 MiB weights."""
import argparse
import base64
import json
from pathlib import Path
from inspect_initializers import inspect

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('graph', type=Path)
parser.add_argument('--output', type=Path, required=True)
args = parser.parse_args()
fixture = dict(graph=base64.b64encode(args.graph.read_bytes()).decode(), manifest=inspect(args.graph))
args.output.write_text('// Generated by tools/create_probe_fixture.py from tools/make_test_model.py.\n'
                       + 'export const FIXTURE = ' + json.dumps(fixture, indent=2) + ';\n')
